--------------------------------------------------------
--  Fichier créé - jeudi-mars-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DISCIPLINE
--------------------------------------------------------

  CREATE TABLE "SHA"."DISCIPLINE" 
   (	"D_ID" NUMBER(1,0), 
	"D_LIBELLE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M1INFO" ;
REM INSERTING into SHA.DISCIPLINE
SET DEFINE OFF;
Insert into SHA.DISCIPLINE (D_ID,D_LIBELLE) values ('1','SKI ALPIN');
Insert into SHA.DISCIPLINE (D_ID,D_LIBELLE) values ('2','SNOWBOARD');
Insert into SHA.DISCIPLINE (D_ID,D_LIBELLE) values ('3','SKI NORDIQUE');
--------------------------------------------------------
--  DDL for Index SYS_C00334291
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHA"."SYS_C00334291" ON "SHA"."DISCIPLINE" ("D_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M1INFO" ;
--------------------------------------------------------
--  Constraints for Table DISCIPLINE
--------------------------------------------------------

  ALTER TABLE "SHA"."DISCIPLINE" MODIFY ("D_LIBELLE" NOT NULL ENABLE);
 
  ALTER TABLE "SHA"."DISCIPLINE" ADD PRIMARY KEY ("D_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M1INFO"  ENABLE;
