--------------------------------------------------------
--  Fichier créé - jeudi-mars-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ELEVE
--------------------------------------------------------

  CREATE TABLE "SHA"."ELEVE" 
   (	"E_ID" NUMBER(5,0), 
	"E_NOM" VARCHAR2(30 BYTE), 
	"E_PRENOM" VARCHAR2(30 BYTE), 
	"E_DATE_NAISS" DATE, 
	"E_NATIONALITE" VARCHAR2(20 BYTE), 
	"E_SEXE" CHAR(1 BYTE), 
	"E_TEL" VARCHAR2(20 BYTE), 
	"AGE" NUMBER(*,0), 
	"TRANCHE" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M1INFO" ;
REM INSERTING into SHA.ELEVE
SET DEFINE OFF;
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('10','D''ARELAUNE','LAURELINE',to_date('25/10/01','DD/MM/RR'),'française','F','06 79 78 79 78','16','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('11','LAGAFFE','GASTON',to_date('12/12/05','DD/MM/RR'),'belge','M',null,'12','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('12','TSUNO','YOKO',to_date('09/11/99','DD/MM/RR'),'japonnaise','F',null,'18','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('13','TOURNESOL','TRYPHON',to_date('23/07/97','DD/MM/RR'),'belge','M',null,'20','20-29 ');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('14','LUCKY','LUKE',to_date('14/08/92','DD/MM/RR'),'etats-unienne','M','07 12 13 54 63','25','20-29 ');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('15','MARTIN','ALIX',to_date('11/05/90','DD/MM/RR'),'italienne','M',null,'27','20-29 ');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('16','BLANDY','JESSICA',to_date('27/03/78','DD/MM/RR'),'française','F','07 66 68 34 44','39','30-39');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('17','BRISEFER','BENOIT',to_date('11/12/87','DD/MM/RR'),'française','M',null,'30','30-39');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('18','CRU','CARMEN',to_date('23/11/34','DD/MM/RR'),'française','F',null,'83','>60');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('19','BURMA','NESTOR',to_date('04/05/59','DD/MM/RR'),'française','M','06 64 65 87 88','58','50-59 ');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('20','CLEMENT','STEPHANE',to_date('01/02/01','DD/MM/RR'),'suisse','M',null,'17','10-19 ');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('21','BRAZIL','BRUNO',to_date('07/08/99','DD/MM/RR'),'etats-unienne','M',null,'18','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('22','BAROUD','BILL',to_date('04/02/98','DD/MM/RR'),'etats-unienne','M',null,'20','20-29');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('23','BLANC-SEC','ADELE',to_date('21/05/77','DD/MM/RR'),'française','F',null,'40','40-49');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('24','TETSUO','SHIMA',to_date('19/10/02','DD/MM/RR'),'japonnaise','M','06 76 77 13 50','15','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('25','HISLAIRE','VIOLETTE',to_date('18/07/05','DD/MM/RR'),'belge','F',null,'12','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('26','MOREL','GINA',to_date('07/09/11','DD/MM/RR'),'française','F',null,'6','<10 ');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('27','BRETECHER','AGRIPPINE',to_date('16/09/95','DD/MM/RR'),'française','F','06 55 03 32 81','22','20-29');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('28','FUTURO','DANY',to_date('09/11/07','DD/MM/RR'),'espagnole','M',null,'10','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('29','QUINO','MAFALDA',to_date('24/01/02','DD/MM/RR'),'argentine','F',null,'16','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('30','DETRITUS','CAIUS',to_date('06/06/06','DD/MM/RR'),'italienne','M','06 07 54 10 23','11','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('31','CAGE','LUKE',to_date('16/07/01','DD/MM/RR'),'etats-unienne','M',null,'16','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('32','ROGERS','STEVEN',to_date('18/03/73','DD/MM/RR'),'etats-unienne','M',null,'44','40-49 ');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('33','XAVIER','CHARLES',to_date('21/10/07','DD/MM/RR'),'etats-unienne','M',null,'10','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('34','TALON','ACHILLE',to_date('24/05/98','DD/MM/RR'),'française','M','07 78 44 20 19','19','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('35','SIMOND','ALICE',to_date('12/01/01','DD/MM/RR'),'française','F',null,'17','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('36','ACHE','ARABELLE',to_date('03/03/88','DD/MM/RR'),'française','F',null,'30','30-39');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('37','WEYLAND','ARIA',to_date('07/08/79','DD/MM/RR'),'belge','F','06 06 75 80 38','38','30-39');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('38','BLOCHE','JEROME',to_date('29/12/94','DD/MM/RR'),'française','M',null,'23','20-29');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('39','CAUVIN','CEDRIC',to_date('11/06/01','DD/MM/RR'),'belge','M',null,'16','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('40','DUBOIS','ROBIN',to_date('27/09/93','DD/MM/RR'),'belge','M',null,'24','20-29');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('41','LEBUT','MARC',to_date('07/07/87','DD/MM/RR'),'belge','M',null,'30','30-39');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('42','BORSHOGOVOCHNYY','LUKA',to_date('21/11/97','DD/MM/RR'),'ukrainienne','M',null,'20','20-29');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('43','LARSSINET','MANU',to_date('07/07/87','DD/MM/RR'),'française','M',null,'30','30-39 ');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('44','HENDERSON','LULU',to_date('11/12/99','DD/MM/RR'),'etats-unienne','F',null,'18','10-19');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('45','SIMPSON','MARGE',to_date('25/08/91','DD/MM/RR'),'etats-unienne','F','06 07 13 43 06','26','20-29 ');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('46','KELLER','KIM',to_date('16/05/95','DD/MM/RR'),'française','F','06 07 13 43 06','22','20-29 ');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('47','SHEDIAC','DRISS',to_date('28/12/85','DD/MM/RR'),'marocaine','M',null,'32','30-39');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('48','SLIM','BOUZID',to_date('24/09/92','DD/MM/RR'),'algérienne','M',null,'25','20-29 ');
Insert into SHA.ELEVE (E_ID,E_NOM,E_PRENOM,E_DATE_NAISS,E_NATIONALITE,E_SEXE,E_TEL,AGE,TRANCHE) values ('49','AOUAMRI','SYLVIE',to_date('04/02/93','DD/MM/RR'),'algérienne','F','06 07 27 56 10','25','20-29 ');
--------------------------------------------------------
--  DDL for Index SYS_C00334334
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHA"."SYS_C00334334" ON "SHA"."ELEVE" ("E_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M1INFO" ;
--------------------------------------------------------
--  Constraints for Table ELEVE
--------------------------------------------------------

  ALTER TABLE "SHA"."ELEVE" MODIFY ("E_NOM" NOT NULL ENABLE);
 
  ALTER TABLE "SHA"."ELEVE" MODIFY ("E_PRENOM" NOT NULL ENABLE);
 
  ALTER TABLE "SHA"."ELEVE" MODIFY ("E_DATE_NAISS" NOT NULL ENABLE);
 
  ALTER TABLE "SHA"."ELEVE" MODIFY ("E_SEXE" NOT NULL ENABLE);
 
  ALTER TABLE "SHA"."ELEVE" ADD PRIMARY KEY ("E_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M1INFO"  ENABLE;
