--------------------------------------------------------
--  Fichier créé - jeudi-mars-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NIVEAU
--------------------------------------------------------

  CREATE TABLE "SHA"."NIVEAU" 
   (	"ID_NIVEAU" NUMBER(*,0), 
	"DISCIPLINE" VARCHAR2(255 BYTE), 
	"N_LIBELLE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M1INFO" ;
REM INSERTING into SHA.NIVEAU
SET DEFINE OFF;
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('20','SKI ALPIN','FLOCON');
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('21','SKI ALPIN','1ERE ETOILE');
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('22','SKI ALPIN','2EME ETOILE');
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('23','SKI ALPIN','3EME ETOILE');
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('24','SKI ALPIN','FLECHE');
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('25','SKI ALPIN','CHAMOIS');
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('41','SNOWBOARD','1ER SNOWBOARD');
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('42','SNOWBOARD','2EME SNOWBOARD');
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('43','SNOWBOARD','3EME SNOWBOARD');
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('50','SKI NORDIQUE','FLOCON');
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('51','SKI NORDIQUE','1ERE ETOILE');
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('52','SKI NORDIQUE','2EME ETOILE');
Insert into SHA.NIVEAU (ID_NIVEAU,DISCIPLINE,N_LIBELLE) values ('53','SKI NORDIQUE','3EME ETOILE');
--------------------------------------------------------
--  DDL for Index SYS_C00334256
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHA"."SYS_C00334256" ON "SHA"."NIVEAU" ("ID_NIVEAU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M1INFO" ;
--------------------------------------------------------
--  Constraints for Table NIVEAU
--------------------------------------------------------

  ALTER TABLE "SHA"."NIVEAU" MODIFY ("ID_NIVEAU" NOT NULL ENABLE);
 
  ALTER TABLE "SHA"."NIVEAU" ADD PRIMARY KEY ("ID_NIVEAU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M1INFO"  ENABLE;
